addSbtPlugin("org.jmotor.sbt"            % "sbt-dependency-updates" % "1.2.7")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"           % "0.4.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"           % "2.5.0")
addSbtPlugin("com.github.sbt"            % "sbt-dynver"             % "5.0.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"           % "0.11.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"          % "2.0.8")
